from enum import StrEnum


class output_keys(StrEnum):
    # Input
    URL = "URL"
    HOMEPAGE_MARKDOWN = "HOMEPAGE_MARKDOWN"
    HOMEPAGE_DATA = "HOMEPAGE_DATA"
    DISCOVERED_LINKS = "DISCOVERED_LINKS"
    DISCOVERY_RESULTS = "DISCOVERY_RESULTS"
    PROBED_LINKS = "PROBED_LINKS"
    SUB_PAGES_URLS = "SUB_PAGES_URLS"
    SCRAPED_SUB_PAGES = "SCRAPED_SUB_PAGES"
    SPEAKERS_DATA = "SPEAKERS_DATA"
    VENUE_DATA = "VENUE_DATA"
    REGISTRATION_DATA = "REGISTRATION_DATA"
    SUB_PAGES_DATA = "SUB_PAGES_DATA"
    CONFERENCE_DATA = "CONFERENCE_DATA"
